import { Bot, HelpCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { fetchReorderPlans } from "../mocks/restockData";
import type { ReorderLine, ReorderPlan } from "../types/restock";
import { UrgencyHeatmap } from "../components/restock/UrgencyHeatmap";
import { DispatchPreviewModal } from "../components/restock/DispatchPreviewModal";

function statusBadge(status: ReorderPlan["status"]) {
  const map: Record<ReorderPlan["status"], string> = {
    pending: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    approved: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    dispatched: "bg-sky-500/15 text-sky-400 border-sky-500/30",
  };
  return `rounded-sm border px-2 py-0.5 text-xs ${map[status]}`;
}

function explainLine(line: ReorderLine): string {
  return `${line.currentCount} detected vs a threshold of ${line.threshold} (~${line.daysOfCover} day${line.daysOfCover === 1 ? "" : "s"} of cover left). ${line.supplier} ships in ${line.leadTimeDays} day${line.leadTimeDays === 1 ? "" : "s"}, so Claude recommends ordering ${line.orderQty} units now to land before stock runs out.`;
}

export default function RestockQueue() {
  const [plans, setPlans] = useState<ReorderPlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showReasoning, setShowReasoning] = useState(false);
  const [modalPlan, setModalPlan] = useState<ReorderPlan | null>(null);

  const fetchPlans = () => {
    fetchReorderPlans()
      .then((res) => setPlans(res.plans.sort((a, b) => b.urgencyScore - a.urgencyScore)))
      .catch(() => setError("Failed to load reorder plans"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchPlans();
  }, []);

  const retry = () => {
    setLoading(true);
    setError(null);
    fetchPlans();
  };

  const approve = (planId: string) => {
    setPlans((prev) =>
      prev.map((p) => (p.planId === planId ? { ...p, status: "approved" } : p))
    );
    setModalPlan(null);
  };

  if (loading) {
    return (
      <div className="grid grid-cols-3 gap-2 sm:grid-cols-6">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="aspect-square animate-pulse rounded-sm bg-[#18181B]" />
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-sm border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">
        {error}{" "}
        <button onClick={retry} className="ml-2 underline">
          Retry
        </button>
      </div>
    );
  }

  const selectedPlan = plans.find((p) => p.planId === selectedId) ?? null;

  return (
    <div className="flex flex-col gap-6 lg:flex-row lg:items-start">
      <div className="min-w-0 flex-1 space-y-6">
        <section>
          <h2 className="mb-3 text-sm font-semibold text-zinc-300">Urgency Heatmap</h2>
          <UrgencyHeatmap
            tiles={plans.map((p) => ({ id: p.planId, label: p.lines[0]?.sku ?? p.planId, urgencyScore: p.urgencyScore }))}
            selectedId={selectedId}
            onSelect={setSelectedId}
          />
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-semibold text-zinc-300">Restock Queue</h2>
          {plans.map((plan) => (
            <div
              key={plan.planId}
              onClick={() => {
                setSelectedId(plan.planId);
                setShowReasoning(false);
              }}
              className={[
                "cursor-pointer rounded-sm border bg-[#0C0C0F] p-3 transition",
                plan.planId === selectedId ? "border-white/40" : "border-[#27272A]",
              ].join(" ")}
            >
              <div className="mb-1 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-zinc-100">{plan.planId}</span>
                  <span className={statusBadge(plan.status)}>{plan.status}</span>
                </div>
                <span className="text-xs text-zinc-500">
                  urgency {(plan.urgencyScore * 100).toFixed(0)}%
                </span>
              </div>

              <div className="mb-2 flex items-center justify-between">
                <div className="flex items-center gap-1 text-xs text-zinc-500">
                  <Bot size={12} className="text-zinc-600" />
                  Generated by {plan.generatedBy}
                </div>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedId(plan.planId);
                    setShowReasoning(true);
                  }}
                  className="flex items-center gap-1 text-xs font-medium text-sky-400 hover:underline"
                >
                  <HelpCircle size={12} />
                  Why this order?
                </button>
              </div>

              <ul className="mb-3 space-y-0.5">
                {plan.lines.map((l) => (
                  <li key={l.sku} className="flex justify-between text-sm text-zinc-300">
                    <span>
                      {l.name} <span className="text-zinc-500">· {l.supplier}</span>
                    </span>
                    <span className="tabular-nums">
                      {l.currentCount}/{l.threshold} → +{l.orderQty}
                    </span>
                  </li>
                ))}
              </ul>

              <div className="flex justify-end">
                <button
                  disabled={plan.status !== "pending"}
                  onClick={(e) => {
                    e.stopPropagation();
                    setModalPlan(plan);
                  }}
                  className="rounded-sm bg-emerald-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-emerald-500 disabled:cursor-not-allowed disabled:bg-zinc-700 disabled:text-zinc-400"
                >
                  {plan.status === "pending" ? "Approve Order" : "Approved"}
                </button>
              </div>
            </div>
          ))}
        </section>
      </div>

      <aside className="w-full shrink-0 space-y-2 lg:sticky lg:top-6 lg:w-80">
        <h2 className="flex items-center gap-1.5 text-sm font-semibold text-zinc-300">
          <Bot size={14} className="text-zinc-500" />
          Agent Decision Rationale
        </h2>
        {selectedPlan ? (
          <div className="rounded-sm border border-[#27272A] bg-[#0C0C0F] p-3">
            <div className="mb-2 flex items-center justify-between">
              <span className="text-sm font-medium text-zinc-100">{selectedPlan.planId}</span>
              <span className="text-xs text-zinc-500">{selectedPlan.generatedBy}</span>
            </div>

            {showReasoning ? (
              <ul className="space-y-3">
                {selectedPlan.lines.map((l) => (
                  <li key={l.sku} className="text-sm leading-relaxed text-zinc-300">
                    <span className="font-medium text-zinc-100">{l.name}</span>
                    <p className="mt-0.5">{explainLine(l)}</p>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm leading-relaxed text-zinc-300">{selectedPlan.rationale}</p>
            )}

            <button
              onClick={() => setShowReasoning((v) => !v)}
              className="mt-3 text-xs font-medium text-sky-400 hover:underline"
            >
              {showReasoning ? "Show summary" : "Why this order?"}
            </button>
          </div>
        ) : (
          <div className="rounded-sm border border-dashed border-[#27272A] p-4 text-sm text-zinc-500">
            Select a plan from the heatmap or queue to see the agent's reasoning.
          </div>
        )}
      </aside>

      <DispatchPreviewModal plan={modalPlan} onCancel={() => setModalPlan(null)} onConfirm={approve} />
    </div>
  );
}
